apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomatoapp-deployment
  labels:
    component: front-end
    version: "1.0.0"
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zomatoapp
  template:
    metadata:
      labels:
        app: zomatoapp
    spec:
      containers:
        - name: zomatoapp-container
          image: henrykum23/zomato:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "500Mi"
              cpu: "200m"
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 8080
          #   initialDelaySeconds: 5
          #   timeoutSeconds: 1
          #   periodSeconds: 5
          #   successThreshold: 1
          #   failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: zomatoapp-service
  namespace: test
spec:
  selector:
    app: zomatoapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zomatoapp-ingress
  namespace: test
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: zomatoapp-service
                port:
                  number: 3000
