apiVersion: apps/v1
kind: Deployment
metadata:
  name: zomatoapp-deployment
  labels:
    app: zomatoapp
  namespace: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zomatoapp
  template:
    metadata:
      labels:
        app: zomatoapp
    spec:
      containers:
      - name: zomatoapp-container
        image: henrykum23/zomato:latest
        ports:
        - containerPort: 3000
        # livenessProbe:
        #   httpGet:
        #     path: /health
        #     port: 8080
        #   initialDelaySeconds: 6
        #   timeoutSeconds: 1
        #   periodSeconds: 5
        #   successThreshold: 1
        #   failureThreshold: 1
---
apiVersion: v1
kind: Service
metadata:
  name: zomatoapp-service
  namespace: test
spec:
  selector:
    app: zomatoapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amazon-ingress
  namespace: test
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: amazon-service
                port:
                  number: 3000