loki:
  enabled: true
  persistence:
    enabled: true
    storageClassName: nfs-client
    size: 1Gi
promtail:
  enabled: true
grafana:
  enabled: false
  sidecar:
    datasources:
      label: ""
      labelValue: ""
      enabled: true
      maxLines: 1000
  image:
    tag: 10.3.3
