# db-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpressdb-deploy
  namespace: test
spec:
  selector:
    matchLabels:
      app: wordpress-db
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress-db
    spec:
      containers:
        - name: wordpressdb-container
          image: postgres:13-alpine
          ports:
            - containerPort: 5432
              name: "postgres"
          env:
            - name: POSTGRES_DB
              value: wordpress
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: pass
          resources:
            limits:
              memory: 10Gi
              cpu: "4"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  labels:
    type: local
    namespace: test
spec:
  claimRef:
    namespace: test
    name: mysql-pvc
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib"
---
# MySQL PVC
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: test
spec:
  volumeName: mysql-pv
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi